# Generated by Django 2.0.7 on 2018-07-30 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='chestxray_image/')),
                ('side', models.CharField(max_length=8)),
                ('gender', models.CharField(max_length=8)),
                ('submitted_on', models.DateField(blank=True, verbose_name='Date')),
                ('description', models.TextField(blank=True, max_length=2048)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
