# Generated by Django 2.0.6 on 2018-07-27 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chestxray', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
